version: '3'
services:
  simple-term-deposit-calculator-cli:
    image: simple-term-deposit-calculator:latest
    container_name: simple-term-deposit-calculator-cli
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 6G
    networks:
      - simple-term-deposit-calculator
    entrypoint: ["simple_term_deposit_calculator", "--deposit-amount", "10000", "--interest-rate", "1.1", "--investment-term", "36", "--interest-paid", "AT_MATURITY"]

  simple-term-deposit-calculator-test:
    image: simple-term-deposit-calculator:latest
    container_name: simple-term-deposit-calculator-test
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 6G
    networks:
      - simple-term-deposit-calculator
    entrypoint: ["pytest"]

  simple-term-deposit-calculator-test-with-debugging:
    image: simple-term-deposit-calculator:latest
    container_name: simple-term-deposit-calculator-test-with-debugging
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 6G
    networks:
      - simple-term-deposit-calculator
    ports:
      - 5678:5678
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "pytest"]

networks:
  simple-term-deposit-calculator:
    driver: bridge
